apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-deployment
  labels:
    app: load-test
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: load-test
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
        - name: load-test-tool
          image: load:1.3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080