apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-deployment
  labels:
    name: load-test
    version: 1.0.0
spec:
  selector:
    matchLabels:
      name: load-test
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
        - name: load-test-tool
          image: load:1.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080